#!/usr/bin/env bash
# PreToolUse on Edit|Write. Two jobs, deliberately unequal in force:
#
#   refuse  local data and build output — a market database, a `.env`, anything under
#           dist/ or node_modules/. These are never source, and a write to one is always
#           a mistake, so this is the one hook here that blocks.
#   warn    a path outside the touch scope the plan declares for this branch's phase.
#           Advisory: staying in scope is a judgement call and widening it deliberately
#           is a legitimate move, so the hook says so once and gets out of the way.
#
# Never blocks on a scope question, and stays silent when the scope cannot be resolved.
set -uo pipefail

input=$(cat)
file=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')
[ -n "$file" ] || exit 0

root="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null)}"
rel=$file
inside=no
case "$file" in "${root:-/nonexistent}"/*) rel=${file#"$root"/}; inside=yes ;; esac
base=$(basename -- "$rel")

deny() {
  jq -n --arg reason "$1" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $reason
    }
  }'
  exit 0
}

case "$base" in
  *.db|*.db-shm|*.db-wal)
    deny "$rel is a SQLite market database. It is generated by the import tools (npm run eod:import, npm run yahoo:fetch) and gitignored; editing it by hand corrupts the dev dataset." ;;
  .env|.env.*)
    deny "$rel holds local secrets. Credentials are set in the shell or in the deploy environment, never written into the repo." ;;
esac

case "$rel" in
  dist/*|dist-ssr/*|node_modules/*|*/node_modules/*)
    deny "$rel is build output or an installed dependency, not source. Edit the source it is built from and run npm run build." ;;
esac

# --- advisory: outside the plan's declared touch scope ---------------------------------

# Only files in the repo have a touch scope. A scratchpad file, or anything else outside
# the project, is not part of the branch and warning about it is pure noise.
[ "$inside" = yes ] || exit 0

scope=$(bash "${root:-.}/.claude/hooks/plan-scope.sh" 2>/dev/null)
[ -n "$scope" ] || exit 0

while IFS= read -r entry; do
  [ -n "$entry" ] || continue
  case "$rel" in
    "$entry"|"$entry"/*) exit 0 ;;
  esac
done <<EOF
$scope
EOF

# Say it once per file per session. A warning repeated on every edit is noise, and noise
# is how an advisory check turns into one that gets ignored.
session=$(printf '%s' "$input" | jq -r '.session_id // "nosession"')
memo="${TMPDIR:-/tmp}/claude-scope-warned-${session}"
if [ -f "$memo" ] && grep -qxF "$rel" "$memo" 2>/dev/null; then exit 0; fi
printf '%s\n' "$rel" >> "$memo"

message="The plan phase this branch is named for declares this touch scope: $(printf '%s' "$scope" | paste -sd ' ' -). ${rel} falls outside it. Either the file does not belong in this branch, or the touch scope needs widening deliberately, which the diary entry has to say."

jq -n --arg message "$message" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    additionalContext: $message
  }
}'
